import turtle
screen = turtle.Screen()
screen.screensize(500, 500)
t=turtle.Turtle()
t.speed(0)
t.hideturtle()


# intro


screen.bgcolor("dodger blue")
t.penup()
t.goto(0, 50)
t.pendown()
t.write("About Me ", align="center", font=("Arial", 34, "bold"))
t.penup()
t.goto(0, -10)
t.pendown()
t.write(" Luke Burg", align="center", font=("Arial", 34, "bold"))
t.penup()
t.goto(0, -60)
t.pendown()
t.write("Press Enter to begin", align="center", font=("Arial", 20, "normal"))

t.penup()
t.goto(150,250)
t.pendown()
screen.addshape('bik.gif')
t.shape('bik.gif')
t.stamp()

t.penup()
t.goto(-150,250)
t.pendown()
screen.addshape('movie.gif')
t.shape('movie.gif')
t.stamp()

t.penup()
t.goto(-65, -170)
t.pendown()
t.pencolor('green')
t.fillcolor('green')
t.begin_fill()
t.forward(150)
t.right(90)
t.forward(150)
t.right(90)
t.forward(150)
t.right(90)
t.forward(150)
t.right(90)
t.end_fill()
# page1
t.pencolor('black')
round = input('Press enter to continue:')
t.clear()
screen.bgcolor('tan')

t.penup()
t.goto(-160,0)
t.pendown()
screen.addshape('mac.gif')
t.shape('mac.gif')
t.stamp()

t.penup()
t.goto(0,0)
t.pendown()
screen.addshape('pizza.gif')
t.shape('pizza.gif')
t.stamp()

t.penup()
t.goto(160,0)
t.pendown()
screen.addshape('burger.gif')
t.shape('burger.gif')
t.stamp()

t.penup()
t.goto(0,200)
t.pendown()
t.write(" Favorite Food", align="center", font=("Arial", 34, "bold"))

t.penup()
t.goto(0,120)
t.pendown()
t.write("Press Enter to continue", align="center", font=("Arial", 25, "normal"))

t.penup()
t.goto(0,-300)
t.pendown()
t.pencolor("tan")
t.fillcolor("light blue")
t.begin_fill()
t.circle(100)
t.end_fill()


round = input('Press enter to continue:')
t.clear()
screen.bgcolor('grey')
t.pencolor('black')
t.penup()
t.goto(0,260)
t.pendown()
t.write("  Hobbies ", align="center", font=("Arial", 40, "bold"))
t.penup()
t.goto(0,170)
t.pendown()
t.write(" 1) bike riding ", align="center", font=("Arial", 20, "bold"))

t.penup()
t.goto(0,140)
t.pendown()
t.write(" 2) Work out", align="center", font=("Arial", 20, "bold"))

t.penup()
t.goto(0,110)
t.pendown()
t.write(" 3) Hike", align="center", font=("Arial", 20, "bold"))

t.penup()
t.goto(0,80)
t.pendown()
t.write(" 4) play video games", align="center", font=("Arial", 20, "bold"))

t.penup()
t.goto(100,0)
t.pendown()
screen.addshape('hike.gif')
t.shape('hike.gif')
t.stamp()

t.penup()
t.goto(-100,0)
t.pendown()
screen.addshape('bike.gif')
t.shape('bike.gif')
t.stamp()

t.penup()
t.goto(0,-150)
t.pendown()
t.write("Press Enter to continue", align="center", font=("Arial", 25, "normal"))


t.penup()
t.goto(-50,-200)
t.pendown()
t.pencolor("yellow")
t.fillcolor("yellow")
t.begin_fill()

t.forward(100)
t.right(144)
t.forward(100)
t.right(144)
t.forward(100)
t.right(144)
t.forward(100)
t.right(144)
t.forward(100)
t.right(144)
t.end_fill()

round = input('Press enter to continue:')
t.clear()
screen.bgcolor('orange')
t.pencolor('black')
t.penup()
t.goto(0,260)
t.pendown()
t.write("  Favorite Movie ", align="center", font=("Arial", 40, "bold"))

t.penup()
t.goto(0,190)
t.pendown()
t.write("  The Godfather ", align="center", font=("Arial", 28, "bold"))

t.penup()
t.goto(100,0)
t.pendown()
screen.addshape('tgod.gif')
t.shape('tgod.gif')
t.stamp()

t.penup()
t.goto(-100,0)
t.pendown()
screen.addshape('god2.gif')
t.shape('god2.gif')
t.stamp()


t.penup()
t.goto(0,120)
t.pendown()
t.write("Press Enter to continue", align="center", font=("Arial", 25, "normal"))

t.penup()
t.goto(-50, -150)
t.pendown()

t.fillcolor("blue")
t.begin_fill()
t.pencolor('blue')
t.forward(100)
t.right(72)
t.forward(100)
t.right(72)
t.forward(100)
t.right(72)
t.forward(100)
t.right(72)

t.end_fill()

round = input('Press enter to continue:')
t.clear()
screen.bgcolor('cyan')

t.pencolor('black')
t.penup()
t.goto(0,260)
t.pendown()
t.write("  Favorite Sport ", align="center", font=("Arial", 40, "bold"))

t.penup()
t.goto(0,190)
t.pendown()
t.write("  Baseball ", align="center", font=("Arial", 28, "bold"))

t.penup()
t.goto(100,0)
t.pendown()
screen.addshape('baseball.gif')
t.shape('baseball.gif')
t.stamp()

t.penup()
t.goto(-100,0)
t.pendown()
screen.addshape('basball2.gif')
t.shape('basball2.gif')
t.stamp()

t.pencolor('grey')
t.penup()
t.goto(-50,-250)
t.pendown()
t.fillcolor("grey")
t.begin_fill()
t.forward(100)
t.right(45)
t.forward(100)
t.right(135)
t.forward(100)
t.right(45)
t.forward(100)
t.right(135)

t.pencolor('black')
t.penup()
t.goto(0,120)
t.pendown()
t.write("Press Enter to end", align="center", font=("Arial", 25, "normal"))

t.end_fill()

round = input('Press enter to continue:')
t.clear()
screen.bgcolor('black')

turtle.done()
